name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  # Atualizado para v4

      - name: Setup Node
        uses: actions/setup-node@v4  # Atualizado para v4
        with:
          node-version: "18"

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4  # Atualizado para v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Permissão para id-token

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4  # Atualizado para v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Atualizado para v4
        with:
          github_token: ${{ secrets.GH_TOKEN }} # Usando o segredo GH_TOKEN
          publish_dir: ./dist
